server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://${URL_DB_ENV}/plaza-powerup     #jdbc:mysql://plaza-comidas.ctnbmskaev1q.us-east-1.rds.amazonaws.com/plaza-powerup
    username: ${USERNAME_DB_ENV}                      #admin
    password: ${PASSWORD_DB_ENV}                      #"#Pr4gm4*"
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${KEYSECRET_SECURITY:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}

feign:
  userApi:
    url: "localhost:8090"
  twilioApi:
    url: "localhost:8092"

management:
  endpoints:
    web:
      exposure:
        include: "*"