name: build, push and deploy

on:
  push:
    branches: [ "cloud-devops" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
        
#    - name: Build with Gradle
#     uses: gradle/gradle-build-action@v2.4.2
    
    - name: Build with Gradle
      run:  ./gradlew clean build
        
    - name: Run tests
      run: |
        chmod +x ./gradlew
        ./gradlew test
      
#   - name: Build and push Docker images
#      uses: docker/build-push-action@v4.1.1
#      with:
#        username: ${{ secrets.USERNAME_DOCKER }}
#        password: ${{ secrets.PASSWORD_DOCKER }}
